#!/bin/bash
# Copies needed files to the SD card

cd
cd peta_build/avnet-digilent-zedboard-2017.1

# Needed for petalinux build
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# Build the files
petalinux-build
petalinux-package --boot --force --fsbl images/linux/zynq_fsbl.elf --fpga ./../design_1_wrapper.bit --u-boot

# Unzip the rootfs
rm -f images/linux/rootfs.cpio
gzip -d -f images/linux/rootfs.cpio.gz

# Copy to SD
cp -f images/linux/BOOT.BIN /run/media/r0583050/78AD-4DD0/
cp -f images/linux/image.ub /run/media/r0583050/78AD-4DD0/
cp -f images/linux/rootfs.cpio /run/media/r0583050/cbd2711f-99e9-41c0-8e22-e400aa213a4a/

cd /run/media/r0583050/cbd2711f-99e9-41c0-8e22-e400aa213a4a/

#Updqck the rootfs
pax -r -c -f rootfs.cpio

cd home/root

# Copy code to the filesystem
mkdir cython
mkdir reports
cd cython
cp /users/start2015/r0583050/Thesis/cython/interface.py .
cp /users/start2015/r0583050/Thesis/cython/monitor.py .
